### PR TITLE
Hydra Agent Console Implementation 

### PR DESCRIPTION
**Pull request by Guttz**
Related to:  https://github.com/HTTP-APIs/hydra-python-agent/issues/124

Draft pull request that will continuously be updated along the next days

### CODE REVIEW

**Comment by xadahiya** [comment]
Can you share some rough mockups first

**Comment by Guttz** [comment]
@xadahiya Sure, today I'll share here where I am/next steps

**Comment by Guttz** [comment]
Here's a picture of the current state:

(Click to expand)
image

This is the developed static version, with some small differences to the Mockup. I've added @xadahiya's suggestion, which is an input field that will contain the raw command. The first icon on the upper toolbar is to hide the HydraGraph(so I can focus only on the right as Chris suggested), the second leads to our home page. I've made one big design change from the mockup that was to use our yellow to match Hydra Eco's colors. The overall aspect should be this with some modifications to functionality as I progress with the actual coding. 

I uploaded  a small video so you can see everything: https://youtu.be/qiXgwdAltJE

**Comment by Guttz** [comment]
#### Next steps
As for the next steps I plan to start to port each of the logic into modular dynamic pieces for it to be built based on the ApiDoc. For that, I'll create a Mock Flask backend(The Agent layer that will forward the commands) which will just return the Mocked processed object that the Frontend needs for now. Later when Vishal is able to join, I think implementing the Flask Endpoints with the actual processing replacing the Mocks would be a good task.

**Comment by Guttz** [comment]
I've created the Flask backend with five endpoints: 
- serve(react app) 
- start-agent(receives hydrus url) 
- hydra-doc(sends hydra doc to frontend).

There are two endpoints I've created but the functionality is yet to be developed: 
- apidoc_graph(send a formatted representation of the api doc), I've already written the format there. 
- send_command(communication endpoint to forward messages to hydrus)
 
With that, I started implementing the dynamic components and the Collection Buttons are already generated based on the ApiDoc.

image

**Comment by Guttz** [comment]
### Next steps

Will finish up the ` Collection buttons component `and proceed with the `operations component `and `properties component`, so they also are generated according to the ApiDoc. After that, I will code the interactions of building the request combining these three components.

**Comment by xadahiya** [comment]
Porting the UI https://github.com/HTTP-APIs/hydra-python-agent-gui

**Comment by Guttz** [comment]
Finished Dynamic buttons and ported it to a modular component. I was having some context problems but everything is ok now, the Console component can already receive the collection component clicked according to the apidoc:

ready

> Porting the UI https://github.com/HTTP-APIs/hydra-python-agent-gui
As we've settled on our last call Friday I'll port this GUI to another repo soon.

**Comment by Guttz** [comment]
One observation @vddesai1871 asked me to raise about the api_doc endpoint on the Flask backend. We have one endpoint for a raw Hydra Doc(used to build the UI) and one for a processed Hydra Doc in Visjs's format(used to build the Graph). The second one could be done both front end and backend. I decided it would be better to do it backend for two reasons:

1. It's really likely that changes in Hydra/Core will be made in the future, and this processing might have to be updated. And as our codebase is mostly in Python, I think having it on the Flask Python Backend side than having it in jsx/React would make it much easier for future contributors to interact when it's necessary.
2. If we want to modify and extend the visualization to show some resources or some other information as a summary or connection to other servers in the future, this could be done only backend side and the Ui doesn't have to be modified and will already be compatible (

**Comment by Guttz** [comment]
This PR was ported to a new repo as commented above.

A small PR was merged(https://github.com/HTTP-APIs/hydra-python-agent/pull/126) related to a small functionality here in the agent that is important for the GUI.

**Pull request closed without merging**
